"""empty message

Revision ID: 03fd9b066f97
Revises: 577eeb5dc68d
Create Date: 2025-12-20 00:17:54.163917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03fd9b066f97'
down_revision = '577eeb5dc68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
