"""empty message

Revision ID: 0dbd53c2d53e
Revises: cf0b8fa03959
Create Date: 2025-12-18 17:14:09.308214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dbd53c2d53e'
down_revision = 'cf0b8fa03959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
