"""empty message

Revision ID: 125ffe03505e
Revises: bfd597a2c814
Create Date: 2025-12-20 15:44:46.055917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125ffe03505e'
down_revision = 'bfd597a2c814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition_hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_room_id', sa.Integer(), nullable=True),
    sa.Column('exhibition_hall_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['exhibition_hall_id'], ['exhibition_hall.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_room_id'], ['storage_room.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    op.drop_table('location')
    op.drop_table('storage_room')
    op.drop_table('exhibition_hall')
    # ### end Alembic commands ###
