"""empty message

Revision ID: 2835debd07df
Revises: 495a8d731806
Create Date: 2025-12-19 17:21:17.277606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2835debd07df'
down_revision = '495a8d731806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_taipei')
    op.drop_table('artifact_beijing')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_5'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('artifact_ibfk_7'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'object_type', ['object_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'motif_and_pattern', ['motif_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'image', ['image_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'form_and_structure', ['form_structure_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'dynasty', ['dynasty_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=True))
        batch_op.alter_column('table_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_timestamp'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('table_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('record_id')

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_7'), 'object_type', ['object_type_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_3'), 'form_and_structure', ['form_structure_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_2'), 'dynasty', ['dynasty_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_4'), 'image', ['image_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_1'), 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('artifact_ibfk_5'), 'motif_and_pattern', ['motif_id'], ['id'])

    op.create_table('artifact_beijing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dynasty_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motif_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('form_structure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('artifact_beijing_ibfk_1')),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], name=op.f('artifact_beijing_ibfk_2')),
    sa.ForeignKeyConstraint(['form_structure_id'], ['form_and_structure.id'], name=op.f('artifact_beijing_ibfk_3')),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('artifact_beijing_ibfk_4')),
    sa.ForeignKeyConstraint(['motif_id'], ['motif_and_pattern.id'], name=op.f('artifact_beijing_ibfk_5')),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.id'], name=op.f('artifact_beijing_ibfk_6')),
    sa.ForeignKeyConstraint(['source_id'], ['museum.id'], name=op.f('artifact_beijing_ibfk_7')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('artifact_taipei',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dynasty_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('image_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motif_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('form_structure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('artifact_taipei_ibfk_1')),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], name=op.f('artifact_taipei_ibfk_2')),
    sa.ForeignKeyConstraint(['form_structure_id'], ['form_and_structure.id'], name=op.f('artifact_taipei_ibfk_3')),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('artifact_taipei_ibfk_4')),
    sa.ForeignKeyConstraint(['motif_id'], ['motif_and_pattern.id'], name=op.f('artifact_taipei_ibfk_5')),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.id'], name=op.f('artifact_taipei_ibfk_6')),
    sa.ForeignKeyConstraint(['source_id'], ['museum.id'], name=op.f('artifact_taipei_ibfk_7')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
