"""empty message

Revision ID: 2a76f12f88a8
Revises: fa4b0d71962d
Create Date: 2025-12-28 15:49:53.929297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a76f12f88a8'
down_revision = 'fa4b0d71962d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    # ### end Alembic commands ###
