"""empty message

Revision ID: 495a8d731806
Revises: 0dbd53c2d53e
Create Date: 2025-12-19 15:38:56.635221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495a8d731806'
down_revision = '0dbd53c2d53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('dynasty_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('motif_id', sa.Integer(), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=True),
    sa.Column('form_structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['form_structure_id'], ['form_and_structure.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['motif_id'], ['motif_and_pattern.id'], ),
    sa.ForeignKeyConstraint(['museum_id'], ['museum.id'], ),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_beijing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'museum', ['source_id'], ['id'])

    with op.batch_alter_table('artifact_taipei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'museum', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_taipei', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('artifact_beijing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_id')

    op.drop_table('artifact')
    op.drop_table('museum')
    # ### end Alembic commands ###
