"""empty message

Revision ID: 577eeb5dc68d
Revises: 2835debd07df
Create Date: 2025-12-20 00:10:09.692984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '577eeb5dc68d'
down_revision = '2835debd07df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_column('number')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
