"""empty message

Revision ID: a7097c55b082
Revises: 03fd9b066f97
Create Date: 2025-12-20 15:05:45.093453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7097c55b082'
down_revision = '03fd9b066f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
