"""empty message

Revision ID: cf0b8fa03959
Revises: e81ba8806dcd
Create Date: 2025-12-18 17:09:49.480118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf0b8fa03959'
down_revision = 'e81ba8806dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('motif_and_pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('form_and_structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
