"""empty message

Revision ID: e81ba8806dcd
Revises: 9ce04b5b416e
Create Date: 2025-12-18 14:47:01.977565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e81ba8806dcd'
down_revision = '9ce04b5b416e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_beijing', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_beijing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
